### PR TITLE
Get rid of php.js dependency.

### PR DESCRIPTION
**Pull request by mttmzr**
If you are interested in getting rid of the phpjs dependency...

phpjs is still needed for the tests.

### CODE REVIEW

**Comment by andymantell** [comment]
Thanks @matt-mx  - could you look into why the tests are failing?

**Comment by mttmzr** [comment]
Damn ES6 (or whatever it is called currently) ;-)

**Comment by mttmzr** [comment]
Oh, just discovered that the Travis CI build is run against NodeJS v0.11.x. I'm running v6.3 locally and all tests are passing. I guess I'm using some funcionality from newer Node versions. 

Have you considered updating the Node version in `.travis.yml` or do you rather keep it as is?

**Comment by mttmzr** [comment]
Finally...

**Comment by andymantell** [comment]
Oh good point, I haven't touched this thing in ages. Best bet would be to update travis so that it runs the tests across multiple versions of node I reckon

**Pull request merged**
